version: '3.8'

services:
  mongodb:
    image: mongo:6.0
    container_name: acs-mongodb
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: one-solution-2025
    volumes:
      - mongodb_data:/data/db
    ports:
      - "27017:27017"

  redis:
    image: redis:7-alpine
    container_name: acs-redis
    restart: unless-stopped
    ports:
      - "6379:6379"

  genieacs-cwmp:
    image: genieacs/genieacs-cwmp:latest
    container_name: acs-cwmp
    restart: unless-stopped
    environment:
      GENIEACS_CWMP_INTERFACE: 0.0.0.0
      GENIEACS_CWMP_PORT: 7547
      GENIEACS_CWMP_SSL: "false"
      GENIEACS_MONGODB_CONNECTION_URL: mongodb://admin:one-solution-2025@mongodb:27017/genieacs?authSource=admin
      GENIEACS_REDIS_CONNECTION_URL: redis://redis:6379
    ports:
      - "7547:7547"
    depends_on:
      - mongodb
      - redis

  genieacs-nbi:
    image: genieacs/genieacs-nbi:latest
    container_name: acs-nbi
    restart: unless-stopped
    environment:
      GENIEACS_NBI_INTERFACE: 0.0.0.0
      GENIEACS_NBI_PORT: 7557
      GENIEACS_MONGODB_CONNECTION_URL: mongodb://admin:one-solution-2025@mongodb:27017/genieacs?authSource=admin
      GENIEACS_REDIS_CONNECTION_URL: redis://redis:6379
    ports:
      - "7557:7557"
    depends_on:
      - mongodb
      - redis

  backend:
    build: ./backend
    container_name: acs-backend
    restart: unless-stopped
    environment:
      NODE_ENV: production
      PORT: 4000
      JWT_SECRET: one-solution-jwt-secret
      GENIEACS_NBI_URL: http://genieacs-nbi:7557
    ports:
      - "4000:4000"
    depends_on:
      - genieacs-nbi

  frontend:
    build: ./frontend
    container_name: acs-frontend
    restart: unless-stopped
    ports:
      - "80:80"
    depends_on:
      - backend

volumes:
  mongodb_data: