version: "3.9"

services:
  mongo:
    image: mongo:4.4
    restart: unless-stopped
    volumes:
      - mongo_data:/data/db

  redis:
    image: redis:6
    restart: unless-stopped

  genieacs-cwmp:
    image: genieacs/genieacs:latest
    command: genieacs-cwmp
    environment:
      - GENIEACS_CWMP_INTERFACE=0.0.0.0
    depends_on:
      - mongo
      - redis
    restart: unless-stopped
    ports:
      - "7547:7547"   # TR-069 endpoint

  genieacs-nbi:
    image: genieacs/genieacs:latest
    command: genieacs-nbi
    depends_on:
      - mongo
      - redis
    restart: unless-stopped
    ports:
      - "7557:7557"   # Northbound API

  genieacs-fs:
    image: genieacs/genieacs:latest
    command: genieacs-fs
    depends_on:
      - mongo
      - redis
    restart: unless-stopped

  genieacs-ui:
    image: genieacs/genieacs:latest
    command: genieacs-ui
    environment:
      - GENIEACS_UI_JWT_SECRET=super-secret-change-me
    depends_on:
      - mongo
      - redis
    restart: unless-stopped
    ports:
      - "3000:3000"   # Original GenieACS UI (optional)

  api:
    build: ./backend
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - GENIEACS_NBI_URL=http://genieacs-nbi:7557
    depends_on:
      - genieacs-nbi
    ports:
      - "4000:4000"   # Custom REST API

  frontend:
    build: ./frontend
    restart: unless-stopped
    depends_on:
      - api
    ports:
      - "80:80"       # Public web portal

volumes:
  mongo_data: 